from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QCoreApplication

class Ui_MainWindow3(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        MainWindow.setMaximumSize(QtCore.QSize(800, 600))
        MainWindow.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.MainLabelEnd = QtWidgets.QLabel(self.centralwidget)
        self.MainLabelEnd.setGeometry(QtCore.QRect(20, 10, 471, 71))
        font = QtGui.QFont()
        font.setPointSize(31)
        self.MainLabelEnd.setFont(font)
        self.MainLabelEnd.setAlignment(QtCore.Qt.AlignCenter)
        self.MainLabelEnd.setObjectName("MainLabelEnd")
        self.EndButton = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: QCoreApplication.instance().quit())
        self.EndButton.setGeometry(QtCore.QRect(220, 440, 391, 71))
        font = QtGui.QFont()
        font.setPointSize(27)
        self.EndButton.setFont(font)
        self.EndButton.setObjectName("EndButton")
        self.TotalCost = QtWidgets.QLabel(self.centralwidget)
        self.TotalCost.setGeometry(QtCore.QRect(120, 370, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.TotalCost.setFont(font)
        self.TotalCost.setObjectName("TotalCost")
        self.EndSummary = QtWidgets.QLabel(self.centralwidget)
        self.EndSummary.setGeometry(QtCore.QRect(120, 100, 511, 251))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.EndSummary.setFont(font)
        self.EndSummary.setText("")
        self.EndSummary.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.EndSummary.setWordWrap(True)
        self.EndSummary.setObjectName("EndSummary")
        self.TotalPrice = QtWidgets.QLabel(self.centralwidget)
        self.TotalPrice.setGeometry(QtCore.QRect(230, 370, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.TotalPrice.setFont(font)
        self.TotalPrice.setText("")
        self.TotalPrice.setObjectName("TotalPrice")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Grocery Shopper"))
        self.MainLabelEnd.setText(_translate("MainWindow", "Grocery Shopper"))
        self.EndButton.setText(_translate("MainWindow", "Done"))
        self.TotalCost.setText(_translate("MainWindow", "Total:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow3()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
